language: node_js
node_js:
 — “6”
install: 
 - npm install
sudo: required
services:
 - docker
after_success:
 - docker build -t Dockerfile .
 - docker tag Dockerfile:latest Dockerfile:1.2
 - docker push dieflo4711/devops_demo:1.2