apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nodejs
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - image: nodejs:latest
        imagePullPolicy: IfNotPresent
        name: nodejs
        ports:
        - containerPort: 8080  