apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - image: dieflo4711/devops_demo:latest
        name: nodejs
        ports:
        - containerPort: 4711  
---

apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 4711
      targetPort: 4711
      nodePort: 31000
  type: NodePort
