apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - image: dieflo4711/devops_demo:8134c1ac14998e803b5c07fbb401fa43318f3409
        imagePullPolicy: Always
        name: nodejs
        ports:
        - containerPort: 4711
        readinessProbe:
          httpGet:
            path: /
            port: 4711
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
