apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - image: dieflo4711/devops_demo@sha256:972723396bd94dbc97292924c81b72c32d96b51236d076c74b68e53580553065
        imagePullPolicy: Always
        name: nodejs
        ports:
        - containerPort: 4711
        readinessProbe:
          httpGet:
            path: /
            port: 4711
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
