apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 4711
      targetPort: 4711
      nodePort: 31000
  type: NodePort